//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 01:16:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "src/main/java/com/boot/rest/jaxb/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.boot.rest.jaxb.domain;
