CREATE TABLE PERSON(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	AGE INT
);

INSERT INTO PERSON(NAME, AGE) VALUES('ABHIMANYU SAHU', 26);
INSERT INTO PERSON(NAME, AGE) VALUES('CHANDRA KISHORE', 32);
INSERT INTO PERSON(NAME, AGE) VALUES('SRINIVAS RAO', 21);
INSERT INTO PERSON(NAME, AGE) VALUES('SURENDRA AGARWAL', 36);
INSERT INTO PERSON(NAME, AGE) VALUES('RAJESH KUMAR', 42);
INSERT INTO PERSON(NAME, AGE) VALUES('NIRANJAN REDDY', 31);